# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f82ee154920ae8862bf79c9b016b924288d3c71b56e6842155f4c1273ed57730cebec1add7de79b11bd575eb64812f2d4350e42c4dc79172449ecf5873d120c6

test:
  secret_key_base: 497b69eefae23ee8f8b07c6354da5250e688953332d14b8937dd5ffcda4300fb839ecd19992843921c4bfcbb103ded76a1fbc57f3323f428b00127e2eef1a13a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
